#ifndef __ANDROID_FILESYSTEM_CONFIG_H__
#define __ANDROID_FILESYSTEM_CONFIG_H__

#define AID_USER    100000

#define AID_SHARED_GID_START    50000
#define AID_SHARED_GID_END      59999

#define AID_ISOLATED_START      99000
#define AID_ISOLATED_END        99999

#endif /* __ANDROID_FILESYSTEM_CONFIG_H__ */